version: '3.9'

services:
  db:
    image: ${DATABASE_TYPE}
    container_name: ${DATABASE_HOSTNAME}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./database:/var/lib/db
    networks:
      - netproject

  core:
    container_name: project_core
    build:
      dockerfile: ./Dockerfile
      # args:
      #   HOST_USER: ${HOST_USER}
      #   HOST_USER_ID: ${HOST_USER_ID}
      #   HOST_GROUP: ${HOST_GROUP}
      #   HOST_GROUP_ID: ${HOST_GROUP_ID}
      #   TIMEZONE: ${TIMEZONE}
    volumes:
      - .:/usr/src/app:rw,cached
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - netproject
volumes:
  .:
networks:
  netproject:
    driver: bridge
